//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Model", "FK_Candidate_To_Employer_Candidates", "Candidates", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ExIDFManagment.DataModel.Candidates), "Candidate_To_Employer", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ExIDFManagment.DataModel.Candidate_To_Employer), true)]
[assembly: EdmRelationshipAttribute("Model", "FK_Candidate_To_Employer_CandidateStatus", "CandidateStatus", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ExIDFManagment.DataModel.CandidateStatus), "Candidate_To_Employer", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ExIDFManagment.DataModel.Candidate_To_Employer), true)]
[assembly: EdmRelationshipAttribute("Model", "FK_Candidate_To_Employer_Employers", "Employers", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ExIDFManagment.DataModel.Employers), "Candidate_To_Employer", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ExIDFManagment.DataModel.Candidate_To_Employer), true)]

#endregion

namespace ExIDFManagment.DataModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Entities object using the connection string found in the 'Entities' section of the application configuration file.
        /// </summary>
        public Entities() : base("name=Entities", "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(string connectionString) : base(connectionString, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(EntityConnection connection) : base(connection, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Candidate_To_Employer> Candidate_To_Employer
        {
            get
            {
                if ((_Candidate_To_Employer == null))
                {
                    _Candidate_To_Employer = base.CreateObjectSet<Candidate_To_Employer>("Candidate_To_Employer");
                }
                return _Candidate_To_Employer;
            }
        }
        private ObjectSet<Candidate_To_Employer> _Candidate_To_Employer;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Candidates> Candidates
        {
            get
            {
                if ((_Candidates == null))
                {
                    _Candidates = base.CreateObjectSet<Candidates>("Candidates");
                }
                return _Candidates;
            }
        }
        private ObjectSet<Candidates> _Candidates;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CompanySize> CompanySize
        {
            get
            {
                if ((_CompanySize == null))
                {
                    _CompanySize = base.CreateObjectSet<CompanySize>("CompanySize");
                }
                return _CompanySize;
            }
        }
        private ObjectSet<CompanySize> _CompanySize;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<InterestSubjects> InterestSubjects
        {
            get
            {
                if ((_InterestSubjects == null))
                {
                    _InterestSubjects = base.CreateObjectSet<InterestSubjects>("InterestSubjects");
                }
                return _InterestSubjects;
            }
        }
        private ObjectSet<InterestSubjects> _InterestSubjects;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Positions> Positions
        {
            get
            {
                if ((_Positions == null))
                {
                    _Positions = base.CreateObjectSet<Positions>("Positions");
                }
                return _Positions;
            }
        }
        private ObjectSet<Positions> _Positions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Positions_To_InterestSubjects> Positions_To_InterestSubjects
        {
            get
            {
                if ((_Positions_To_InterestSubjects == null))
                {
                    _Positions_To_InterestSubjects = base.CreateObjectSet<Positions_To_InterestSubjects>("Positions_To_InterestSubjects");
                }
                return _Positions_To_InterestSubjects;
            }
        }
        private ObjectSet<Positions_To_InterestSubjects> _Positions_To_InterestSubjects;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Locations> Locations
        {
            get
            {
                if ((_Locations == null))
                {
                    _Locations = base.CreateObjectSet<Locations>("Locations");
                }
                return _Locations;
            }
        }
        private ObjectSet<Locations> _Locations;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Location> Location
        {
            get
            {
                if ((_Location == null))
                {
                    _Location = base.CreateObjectSet<Location>("Location");
                }
                return _Location;
            }
        }
        private ObjectSet<Location> _Location;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CandidateStatus> CandidateStatus
        {
            get
            {
                if ((_CandidateStatus == null))
                {
                    _CandidateStatus = base.CreateObjectSet<CandidateStatus>("CandidateStatus");
                }
                return _CandidateStatus;
            }
        }
        private ObjectSet<CandidateStatus> _CandidateStatus;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Employers> Employers
        {
            get
            {
                if ((_Employers == null))
                {
                    _Employers = base.CreateObjectSet<Employers>("Employers");
                }
                return _Employers;
            }
        }
        private ObjectSet<Employers> _Employers;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Candidate_To_Employer EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCandidate_To_Employer(Candidate_To_Employer candidate_To_Employer)
        {
            base.AddObject("Candidate_To_Employer", candidate_To_Employer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Candidates EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCandidates(Candidates candidates)
        {
            base.AddObject("Candidates", candidates);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CompanySize EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCompanySize(CompanySize companySize)
        {
            base.AddObject("CompanySize", companySize);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the InterestSubjects EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToInterestSubjects(InterestSubjects interestSubjects)
        {
            base.AddObject("InterestSubjects", interestSubjects);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Positions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPositions(Positions positions)
        {
            base.AddObject("Positions", positions);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Positions_To_InterestSubjects EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPositions_To_InterestSubjects(Positions_To_InterestSubjects positions_To_InterestSubjects)
        {
            base.AddObject("Positions_To_InterestSubjects", positions_To_InterestSubjects);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Locations EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLocations(Locations locations)
        {
            base.AddObject("Locations", locations);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Location EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLocation(Location location)
        {
            base.AddObject("Location", location);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CandidateStatus EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCandidateStatus(CandidateStatus candidateStatus)
        {
            base.AddObject("CandidateStatus", candidateStatus);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Employers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEmployers(Employers employers)
        {
            base.AddObject("Employers", employers);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="Candidate_To_Employer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Candidate_To_Employer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Candidate_To_Employer object.
        /// </summary>
        /// <param name="pK">Initial value of the PK property.</param>
        /// <param name="candidate_FK">Initial value of the Candidate_FK property.</param>
        /// <param name="employer_FK">Initial value of the Employer_FK property.</param>
        public static Candidate_To_Employer CreateCandidate_To_Employer(global::System.String pK, global::System.String candidate_FK, global::System.String employer_FK)
        {
            Candidate_To_Employer candidate_To_Employer = new Candidate_To_Employer();
            candidate_To_Employer.PK = pK;
            candidate_To_Employer.Candidate_FK = candidate_FK;
            candidate_To_Employer.Employer_FK = employer_FK;
            return candidate_To_Employer;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PK
        {
            get
            {
                return _PK;
            }
            set
            {
                if (_PK != value)
                {
                    OnPKChanging(value);
                    ReportPropertyChanging("PK");
                    _PK = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("PK");
                    OnPKChanged();
                }
            }
        }
        private global::System.String _PK;
        partial void OnPKChanging(global::System.String value);
        partial void OnPKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Candidate_FK
        {
            get
            {
                return _Candidate_FK;
            }
            set
            {
                OnCandidate_FKChanging(value);
                ReportPropertyChanging("Candidate_FK");
                _Candidate_FK = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Candidate_FK");
                OnCandidate_FKChanged();
            }
        }
        private global::System.String _Candidate_FK;
        partial void OnCandidate_FKChanging(global::System.String value);
        partial void OnCandidate_FKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Employer_FK
        {
            get
            {
                return _Employer_FK;
            }
            set
            {
                OnEmployer_FKChanging(value);
                ReportPropertyChanging("Employer_FK");
                _Employer_FK = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Employer_FK");
                OnEmployer_FKChanged();
            }
        }
        private global::System.String _Employer_FK;
        partial void OnEmployer_FKChanging(global::System.String value);
        partial void OnEmployer_FKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comment
        {
            get
            {
                return _Comment;
            }
            set
            {
                OnCommentChanging(value);
                ReportPropertyChanging("Comment");
                _Comment = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Comment");
                OnCommentChanged();
            }
        }
        private global::System.String _Comment;
        partial void OnCommentChanging(global::System.String value);
        partial void OnCommentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Expose_Date
        {
            get
            {
                return _Expose_Date;
            }
            set
            {
                OnExpose_DateChanging(value);
                ReportPropertyChanging("Expose_Date");
                _Expose_Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Expose_Date");
                OnExpose_DateChanged();
            }
        }
        private Nullable<global::System.DateTime> _Expose_Date;
        partial void OnExpose_DateChanging(Nullable<global::System.DateTime> value);
        partial void OnExpose_DateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "FK_Candidate_To_Employer_Candidates", "Candidates")]
        public Candidates Candidates
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Candidates>("Model.FK_Candidate_To_Employer_Candidates", "Candidates").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Candidates>("Model.FK_Candidate_To_Employer_Candidates", "Candidates").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Candidates> CandidatesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Candidates>("Model.FK_Candidate_To_Employer_Candidates", "Candidates");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Candidates>("Model.FK_Candidate_To_Employer_Candidates", "Candidates", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "FK_Candidate_To_Employer_CandidateStatus", "CandidateStatus")]
        public CandidateStatus CandidateStatus
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CandidateStatus>("Model.FK_Candidate_To_Employer_CandidateStatus", "CandidateStatus").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CandidateStatus>("Model.FK_Candidate_To_Employer_CandidateStatus", "CandidateStatus").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CandidateStatus> CandidateStatusReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CandidateStatus>("Model.FK_Candidate_To_Employer_CandidateStatus", "CandidateStatus");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CandidateStatus>("Model.FK_Candidate_To_Employer_CandidateStatus", "CandidateStatus", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "FK_Candidate_To_Employer_Employers", "Employers")]
        public Employers Employers
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employers>("Model.FK_Candidate_To_Employer_Employers", "Employers").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employers>("Model.FK_Candidate_To_Employer_Employers", "Employers").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Employers> EmployersReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employers>("Model.FK_Candidate_To_Employer_Employers", "Employers");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Employers>("Model.FK_Candidate_To_Employer_Employers", "Employers", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="Candidates")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Candidates : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Candidates object.
        /// </summary>
        /// <param name="pK">Initial value of the PK property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="isDeleted">Initial value of the IsDeleted property.</param>
        public static Candidates CreateCandidates(global::System.String pK, global::System.String name, global::System.Int32 isDeleted)
        {
            Candidates candidates = new Candidates();
            candidates.PK = pK;
            candidates.Name = name;
            candidates.IsDeleted = isDeleted;
            return candidates;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PK
        {
            get
            {
                return _PK;
            }
            set
            {
                if (_PK != value)
                {
                    OnPKChanging(value);
                    ReportPropertyChanging("PK");
                    _PK = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("PK");
                    OnPKChanged();
                }
            }
        }
        private global::System.String _PK;
        partial void OnPKChanging(global::System.String value);
        partial void OnPKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateOfBirth
        {
            get
            {
                return _DateOfBirth;
            }
            set
            {
                OnDateOfBirthChanging(value);
                ReportPropertyChanging("DateOfBirth");
                _DateOfBirth = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateOfBirth");
                OnDateOfBirthChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateOfBirth;
        partial void OnDateOfBirthChanging(Nullable<global::System.DateTime> value);
        partial void OnDateOfBirthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Location
        {
            get
            {
                return _Location;
            }
            set
            {
                OnLocationChanging(value);
                ReportPropertyChanging("Location");
                _Location = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Location");
                OnLocationChanged();
            }
        }
        private global::System.String _Location;
        partial void OnLocationChanging(global::System.String value);
        partial void OnLocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Expected_Salary
        {
            get
            {
                return _Expected_Salary;
            }
            set
            {
                OnExpected_SalaryChanging(value);
                ReportPropertyChanging("Expected_Salary");
                _Expected_Salary = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Expected_Salary");
                OnExpected_SalaryChanged();
            }
        }
        private Nullable<global::System.Int32> _Expected_Salary;
        partial void OnExpected_SalaryChanging(Nullable<global::System.Int32> value);
        partial void OnExpected_SalaryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Military_Unit
        {
            get
            {
                return _Military_Unit;
            }
            set
            {
                OnMilitary_UnitChanging(value);
                ReportPropertyChanging("Military_Unit");
                _Military_Unit = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Military_Unit");
                OnMilitary_UnitChanged();
            }
        }
        private global::System.String _Military_Unit;
        partial void OnMilitary_UnitChanging(global::System.String value);
        partial void OnMilitary_UnitChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CV_Path
        {
            get
            {
                return _CV_Path;
            }
            set
            {
                OnCV_PathChanging(value);
                ReportPropertyChanging("CV_Path");
                _CV_Path = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CV_Path");
                OnCV_PathChanged();
            }
        }
        private global::System.String _CV_Path;
        partial void OnCV_PathChanging(global::System.String value);
        partial void OnCV_PathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IsDeleted
        {
            get
            {
                return _IsDeleted;
            }
            set
            {
                OnIsDeletedChanging(value);
                ReportPropertyChanging("IsDeleted");
                _IsDeleted = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsDeleted");
                OnIsDeletedChanged();
            }
        }
        private global::System.Int32 _IsDeleted;
        partial void OnIsDeletedChanging(global::System.Int32 value);
        partial void OnIsDeletedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreationTime
        {
            get
            {
                return _CreationTime;
            }
            set
            {
                OnCreationTimeChanging(value);
                ReportPropertyChanging("CreationTime");
                _CreationTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreationTime");
                OnCreationTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreationTime;
        partial void OnCreationTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnCreationTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsRelevant
        {
            get
            {
                return _IsRelevant;
            }
            set
            {
                OnIsRelevantChanging(value);
                ReportPropertyChanging("IsRelevant");
                _IsRelevant = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsRelevant");
                OnIsRelevantChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsRelevant;
        partial void OnIsRelevantChanging(Nullable<global::System.Boolean> value);
        partial void OnIsRelevantChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "FK_Candidate_To_Employer_Candidates", "Candidate_To_Employer")]
        public EntityCollection<Candidate_To_Employer> Candidate_To_Employer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Candidate_To_Employer>("Model.FK_Candidate_To_Employer_Candidates", "Candidate_To_Employer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Candidate_To_Employer>("Model.FK_Candidate_To_Employer_Candidates", "Candidate_To_Employer", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="CandidateStatus")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CandidateStatus : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CandidateStatus object.
        /// </summary>
        /// <param name="status">Initial value of the Status property.</param>
        public static CandidateStatus CreateCandidateStatus(global::System.String status)
        {
            CandidateStatus candidateStatus = new CandidateStatus();
            candidateStatus.Status = status;
            return candidateStatus;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                if (_Status != value)
                {
                    OnStatusChanging(value);
                    ReportPropertyChanging("Status");
                    _Status = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Status");
                    OnStatusChanged();
                }
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "FK_Candidate_To_Employer_CandidateStatus", "Candidate_To_Employer")]
        public EntityCollection<Candidate_To_Employer> Candidate_To_Employer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Candidate_To_Employer>("Model.FK_Candidate_To_Employer_CandidateStatus", "Candidate_To_Employer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Candidate_To_Employer>("Model.FK_Candidate_To_Employer_CandidateStatus", "Candidate_To_Employer", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="CompanySize")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CompanySize : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CompanySize object.
        /// </summary>
        /// <param name="pK">Initial value of the PK property.</param>
        /// <param name="companySize1">Initial value of the CompanySize1 property.</param>
        public static CompanySize CreateCompanySize(global::System.String pK, global::System.String companySize1)
        {
            CompanySize companySize = new CompanySize();
            companySize.PK = pK;
            companySize.CompanySize1 = companySize1;
            return companySize;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PK
        {
            get
            {
                return _PK;
            }
            set
            {
                if (_PK != value)
                {
                    OnPKChanging(value);
                    ReportPropertyChanging("PK");
                    _PK = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("PK");
                    OnPKChanged();
                }
            }
        }
        private global::System.String _PK;
        partial void OnPKChanging(global::System.String value);
        partial void OnPKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CompanySize1
        {
            get
            {
                return _CompanySize1;
            }
            set
            {
                if (_CompanySize1 != value)
                {
                    OnCompanySize1Changing(value);
                    ReportPropertyChanging("CompanySize1");
                    _CompanySize1 = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("CompanySize1");
                    OnCompanySize1Changed();
                }
            }
        }
        private global::System.String _CompanySize1;
        partial void OnCompanySize1Changing(global::System.String value);
        partial void OnCompanySize1Changed();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="Employers")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Employers : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Employers object.
        /// </summary>
        /// <param name="pK">Initial value of the PK property.</param>
        /// <param name="companyName">Initial value of the CompanyName property.</param>
        public static Employers CreateEmployers(global::System.String pK, global::System.String companyName)
        {
            Employers employers = new Employers();
            employers.PK = pK;
            employers.CompanyName = companyName;
            return employers;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PK
        {
            get
            {
                return _PK;
            }
            set
            {
                if (_PK != value)
                {
                    OnPKChanging(value);
                    ReportPropertyChanging("PK");
                    _PK = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("PK");
                    OnPKChanged();
                }
            }
        }
        private global::System.String _PK;
        partial void OnPKChanging(global::System.String value);
        partial void OnPKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CompanyName
        {
            get
            {
                return _CompanyName;
            }
            set
            {
                OnCompanyNameChanging(value);
                ReportPropertyChanging("CompanyName");
                _CompanyName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CompanyName");
                OnCompanyNameChanged();
            }
        }
        private global::System.String _CompanyName;
        partial void OnCompanyNameChanging(global::System.String value);
        partial void OnCompanyNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Location
        {
            get
            {
                return _Location;
            }
            set
            {
                OnLocationChanging(value);
                ReportPropertyChanging("Location");
                _Location = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Location");
                OnLocationChanged();
            }
        }
        private global::System.String _Location;
        partial void OnLocationChanging(global::System.String value);
        partial void OnLocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CompanySizeFK
        {
            get
            {
                return _CompanySizeFK;
            }
            set
            {
                OnCompanySizeFKChanging(value);
                ReportPropertyChanging("CompanySizeFK");
                _CompanySizeFK = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CompanySizeFK");
                OnCompanySizeFKChanged();
            }
        }
        private Nullable<global::System.Int32> _CompanySizeFK;
        partial void OnCompanySizeFKChanging(Nullable<global::System.Int32> value);
        partial void OnCompanySizeFKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ContactName
        {
            get
            {
                return _ContactName;
            }
            set
            {
                OnContactNameChanging(value);
                ReportPropertyChanging("ContactName");
                _ContactName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ContactName");
                OnContactNameChanged();
            }
        }
        private global::System.String _ContactName;
        partial void OnContactNameChanging(global::System.String value);
        partial void OnContactNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ContactEmail
        {
            get
            {
                return _ContactEmail;
            }
            set
            {
                OnContactEmailChanging(value);
                ReportPropertyChanging("ContactEmail");
                _ContactEmail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ContactEmail");
                OnContactEmailChanged();
            }
        }
        private global::System.String _ContactEmail;
        partial void OnContactEmailChanging(global::System.String value);
        partial void OnContactEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ContractPath
        {
            get
            {
                return _ContractPath;
            }
            set
            {
                OnContractPathChanging(value);
                ReportPropertyChanging("ContractPath");
                _ContractPath = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ContractPath");
                OnContractPathChanged();
            }
        }
        private global::System.String _ContractPath;
        partial void OnContractPathChanging(global::System.String value);
        partial void OnContractPathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comment
        {
            get
            {
                return _Comment;
            }
            set
            {
                OnCommentChanging(value);
                ReportPropertyChanging("Comment");
                _Comment = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Comment");
                OnCommentChanged();
            }
        }
        private global::System.String _Comment;
        partial void OnCommentChanging(global::System.String value);
        partial void OnCommentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreationTime
        {
            get
            {
                return _CreationTime;
            }
            set
            {
                OnCreationTimeChanging(value);
                ReportPropertyChanging("CreationTime");
                _CreationTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreationTime");
                OnCreationTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreationTime;
        partial void OnCreationTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnCreationTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsRelevant
        {
            get
            {
                return _IsRelevant;
            }
            set
            {
                OnIsRelevantChanging(value);
                ReportPropertyChanging("IsRelevant");
                _IsRelevant = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsRelevant");
                OnIsRelevantChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsRelevant;
        partial void OnIsRelevantChanging(Nullable<global::System.Boolean> value);
        partial void OnIsRelevantChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CompanyDescription
        {
            get
            {
                return _CompanyDescription;
            }
            set
            {
                OnCompanyDescriptionChanging(value);
                ReportPropertyChanging("CompanyDescription");
                _CompanyDescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CompanyDescription");
                OnCompanyDescriptionChanged();
            }
        }
        private global::System.String _CompanyDescription;
        partial void OnCompanyDescriptionChanging(global::System.String value);
        partial void OnCompanyDescriptionChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "FK_Candidate_To_Employer_Employers", "Candidate_To_Employer")]
        public EntityCollection<Candidate_To_Employer> Candidate_To_Employer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Candidate_To_Employer>("Model.FK_Candidate_To_Employer_Employers", "Candidate_To_Employer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Candidate_To_Employer>("Model.FK_Candidate_To_Employer_Employers", "Candidate_To_Employer", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="InterestSubjects")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class InterestSubjects : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new InterestSubjects object.
        /// </summary>
        /// <param name="pK">Initial value of the PK property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static InterestSubjects CreateInterestSubjects(global::System.String pK, global::System.String name)
        {
            InterestSubjects interestSubjects = new InterestSubjects();
            interestSubjects.PK = pK;
            interestSubjects.Name = name;
            return interestSubjects;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PK
        {
            get
            {
                return _PK;
            }
            set
            {
                if (_PK != value)
                {
                    OnPKChanging(value);
                    ReportPropertyChanging("PK");
                    _PK = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("PK");
                    OnPKChanged();
                }
            }
        }
        private global::System.String _PK;
        partial void OnPKChanging(global::System.String value);
        partial void OnPKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                if (_Name != value)
                {
                    OnNameChanging(value);
                    ReportPropertyChanging("Name");
                    _Name = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Name");
                    OnNameChanged();
                }
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comment
        {
            get
            {
                return _Comment;
            }
            set
            {
                OnCommentChanging(value);
                ReportPropertyChanging("Comment");
                _Comment = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Comment");
                OnCommentChanged();
            }
        }
        private global::System.String _Comment;
        partial void OnCommentChanging(global::System.String value);
        partial void OnCommentChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="Location")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Location : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Location object.
        /// </summary>
        /// <param name="location1">Initial value of the Location1 property.</param>
        public static Location CreateLocation(global::System.String location1)
        {
            Location location = new Location();
            location.Location1 = location1;
            return location;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Location1
        {
            get
            {
                return _Location1;
            }
            set
            {
                if (_Location1 != value)
                {
                    OnLocation1Changing(value);
                    ReportPropertyChanging("Location1");
                    _Location1 = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Location1");
                    OnLocation1Changed();
                }
            }
        }
        private global::System.String _Location1;
        partial void OnLocation1Changing(global::System.String value);
        partial void OnLocation1Changed();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="Locations")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Locations : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Locations object.
        /// </summary>
        /// <param name="location">Initial value of the Location property.</param>
        public static Locations CreateLocations(global::System.String location)
        {
            Locations locations = new Locations();
            locations.Location = location;
            return locations;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Location
        {
            get
            {
                return _Location;
            }
            set
            {
                if (_Location != value)
                {
                    OnLocationChanging(value);
                    ReportPropertyChanging("Location");
                    _Location = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Location");
                    OnLocationChanged();
                }
            }
        }
        private global::System.String _Location;
        partial void OnLocationChanging(global::System.String value);
        partial void OnLocationChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="Positions")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Positions : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Positions object.
        /// </summary>
        /// <param name="pK">Initial value of the PK property.</param>
        /// <param name="employer_FK">Initial value of the Employer_FK property.</param>
        /// <param name="dateCreated">Initial value of the DateCreated property.</param>
        public static Positions CreatePositions(global::System.String pK, global::System.String employer_FK, global::System.DateTime dateCreated)
        {
            Positions positions = new Positions();
            positions.PK = pK;
            positions.Employer_FK = employer_FK;
            positions.DateCreated = dateCreated;
            return positions;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PK
        {
            get
            {
                return _PK;
            }
            set
            {
                if (_PK != value)
                {
                    OnPKChanging(value);
                    ReportPropertyChanging("PK");
                    _PK = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("PK");
                    OnPKChanged();
                }
            }
        }
        private global::System.String _PK;
        partial void OnPKChanging(global::System.String value);
        partial void OnPKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Employer_FK
        {
            get
            {
                return _Employer_FK;
            }
            set
            {
                if (_Employer_FK != value)
                {
                    OnEmployer_FKChanging(value);
                    ReportPropertyChanging("Employer_FK");
                    _Employer_FK = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Employer_FK");
                    OnEmployer_FKChanged();
                }
            }
        }
        private global::System.String _Employer_FK;
        partial void OnEmployer_FKChanging(global::System.String value);
        partial void OnEmployer_FKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateCreated
        {
            get
            {
                return _DateCreated;
            }
            set
            {
                if (_DateCreated != value)
                {
                    OnDateCreatedChanging(value);
                    ReportPropertyChanging("DateCreated");
                    _DateCreated = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DateCreated");
                    OnDateCreatedChanged();
                }
            }
        }
        private global::System.DateTime _DateCreated;
        partial void OnDateCreatedChanging(global::System.DateTime value);
        partial void OnDateCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IsRelevant
        {
            get
            {
                return _IsRelevant;
            }
            set
            {
                OnIsRelevantChanging(value);
                ReportPropertyChanging("IsRelevant");
                _IsRelevant = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsRelevant");
                OnIsRelevantChanged();
            }
        }
        private Nullable<global::System.Int32> _IsRelevant;
        partial void OnIsRelevantChanging(Nullable<global::System.Int32> value);
        partial void OnIsRelevantChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="Positions_To_InterestSubjects")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Positions_To_InterestSubjects : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Positions_To_InterestSubjects object.
        /// </summary>
        /// <param name="pK">Initial value of the PK property.</param>
        /// <param name="poisition_FK">Initial value of the Poisition_FK property.</param>
        /// <param name="interestSubject_FK">Initial value of the InterestSubject_FK property.</param>
        public static Positions_To_InterestSubjects CreatePositions_To_InterestSubjects(global::System.String pK, global::System.String poisition_FK, global::System.String interestSubject_FK)
        {
            Positions_To_InterestSubjects positions_To_InterestSubjects = new Positions_To_InterestSubjects();
            positions_To_InterestSubjects.PK = pK;
            positions_To_InterestSubjects.Poisition_FK = poisition_FK;
            positions_To_InterestSubjects.InterestSubject_FK = interestSubject_FK;
            return positions_To_InterestSubjects;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PK
        {
            get
            {
                return _PK;
            }
            set
            {
                if (_PK != value)
                {
                    OnPKChanging(value);
                    ReportPropertyChanging("PK");
                    _PK = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("PK");
                    OnPKChanged();
                }
            }
        }
        private global::System.String _PK;
        partial void OnPKChanging(global::System.String value);
        partial void OnPKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Poisition_FK
        {
            get
            {
                return _Poisition_FK;
            }
            set
            {
                if (_Poisition_FK != value)
                {
                    OnPoisition_FKChanging(value);
                    ReportPropertyChanging("Poisition_FK");
                    _Poisition_FK = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Poisition_FK");
                    OnPoisition_FKChanged();
                }
            }
        }
        private global::System.String _Poisition_FK;
        partial void OnPoisition_FKChanging(global::System.String value);
        partial void OnPoisition_FKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String InterestSubject_FK
        {
            get
            {
                return _InterestSubject_FK;
            }
            set
            {
                if (_InterestSubject_FK != value)
                {
                    OnInterestSubject_FKChanging(value);
                    ReportPropertyChanging("InterestSubject_FK");
                    _InterestSubject_FK = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("InterestSubject_FK");
                    OnInterestSubject_FKChanged();
                }
            }
        }
        private global::System.String _InterestSubject_FK;
        partial void OnInterestSubject_FKChanging(global::System.String value);
        partial void OnInterestSubject_FKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IsMandatory
        {
            get
            {
                return _IsMandatory;
            }
            set
            {
                OnIsMandatoryChanging(value);
                ReportPropertyChanging("IsMandatory");
                _IsMandatory = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsMandatory");
                OnIsMandatoryChanged();
            }
        }
        private Nullable<global::System.Int32> _IsMandatory;
        partial void OnIsMandatoryChanging(Nullable<global::System.Int32> value);
        partial void OnIsMandatoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comment
        {
            get
            {
                return _Comment;
            }
            set
            {
                OnCommentChanging(value);
                ReportPropertyChanging("Comment");
                _Comment = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Comment");
                OnCommentChanged();
            }
        }
        private global::System.String _Comment;
        partial void OnCommentChanging(global::System.String value);
        partial void OnCommentChanged();

        #endregion
    
    }

    #endregion
    
}
